"""criando tabelas de treinos

Revision ID: d1ddca58fbf6
Revises: 3c4f3ee68608
Create Date: 2026-03-22 17:38:56.134081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ddca58fbf6'
down_revision: Union[str, Sequence[str], None] = '3c4f3ee68608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treinos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('objetivo', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercicios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticoes', sa.Integer(), nullable=True),
    sa.Column('carga', sa.Float(), nullable=True),
    sa.Column('treino_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['treino_id'], ['treinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercicios')
    op.drop_table('treinos')
    # ### end Alembic commands ###
